package com.universal.app

object AmharicAudioPrompts {
    val promptMap = mapOf(
        1 to R.raw.prompt_01,   // "ካሜራ በመክፈት ላይ"
        2 to R.raw.prompt_02,   // "ካሜራ ተዘግቷል"
        3 to R.raw.prompt_03,   // "ካሜራው ገና አልተከፈተም"
        4 to R.raw.prompt_04,   // "ካሜራው ዝግጁ ነው"
        5 to R.raw.prompt_05,   // "ፎቶ በማንሳት ላይ"
        6 to R.raw.prompt_06,   // "ማነሻው አልታየም..."
        7 to R.raw.prompt_07,   // "የሚላክ ፎቶ የለም"
        8 to R.raw.prompt_08,   // "ተገናኝቷል"
        9 to R.raw.prompt_09,   // "የስክሪን መቆለፊያ ተነሳ..."
        10 to R.raw.prompt_10,  // "የኤርፎን መቆጣጠሪያ ዝግጁ ነው"
        11 to R.raw.prompt_11,  // "የኤርፎን መቆጣጠሪያ ተዘግቷል"
        12 to R.raw.prompt_12,  // "ይሄ ገጽታ አንድሮይድ ዘጠኝ ይፈልጋል"
        13 to R.raw.prompt_13,  // "ሲስተሙ ተደምስሷል..."
        14 to R.raw.prompt_14,  // "ስክሪን ጠፍቷል"
        15 to R.raw.prompt_15,  // "ስክሪኑ በርቷል"
        16 to R.raw.prompt_16,  // "ስክሪኑን መቀስቀስ አልተቻለም..."
        17 to R.raw.prompt_17,  // "ፎቶዎቹን መላክ አልተቻለም..."
        18 to R.raw.prompt_18,  // "ሲስተሙ ስራ ላይ ነው..."
        19 to R.raw.prompt_19,  // "ፎቶዎች ለመሰራት በመዘጋጀት ላይ ናቸው"
        20 to R.raw.prompt_20,  // "በመላክ ላይ እያለ ኢንተርኔት ተቋረጠ"
        21 to R.raw.prompt_21,  // "ፎቶዎቹን የሚቀበለው ሲስተም እምቢ ብሏል"
        22 to R.raw.prompt_22,  // "ፎቶ መላክ ተጠናቋል..."
        23 to R.raw.prompt_23,  // "የፎቶው ጥራት ዝቅተኛ ነው..."
        24 to R.raw.prompt_24,  // "በክላውድ ስራ ላይ ስህተት አጋጥሟል"
        25 to R.raw.prompt_25,  // "ኤአይ አሁንም ገና እየሰራ ነው"
        26 to R.raw.prompt_26,  // "የስራው ጊዜው አልፏል..."
        27 to R.raw.prompt_27,  // "ስራው ተጠናቋል፡ በማመሳሰል ላይ"
        28 to R.raw.prompt_28,  // "ሥራውን ማስጀመር አልተቻለም"
        29 to R.raw.prompt_29,  // "መልሶችን በማጫወት ላይ"
        30 to R.raw.prompt_30,  // "አሰሳ ክፍት ነው..."
        31 to R.raw.prompt_31,  // "የተጫነ መልስ የለም"
        32 to R.raw.prompt_32,  // "አሁንም በማሰብ ላይ..."
        33 to R.raw.prompt_33,  // "የሚቀጥለውን መልስ በመጠበቅ ላይ"
        34 to R.raw.prompt_34,  // "የሚቀጥለው መልስ"
        35 to R.raw.prompt_35,  // "ያለፈው መልስ"
        36 to R.raw.prompt_36,  // "ዝርዝሩ አልቋል..."
        37 to R.raw.prompt_37,  // "የዚህ አይነት መልስ የለም"
        38 to R.raw.prompt_38,  // "ቆሟል"
        39 to R.raw.prompt_39,  // "ቀጥሏል"
        40 to R.raw.prompt_40,  // "አንድ መልስ ብቻ ነው ያለው"
        41 to R.raw.prompt_41,  // "በዝርዝር የተሰሩ መልሶች"
        42 to R.raw.prompt_42,  // "እውነት ወይም ሐሰት"
        43 to R.raw.prompt_43,  // "ምርጫ"
        44 to R.raw.prompt_44,  // "አዛምድ"
        45 to R.raw.prompt_45,  // "ባዶ ቦታ ሙላ"
        46 to R.raw.prompt_46,  // "አጭር መልሶች"
        47 to R.raw.prompt_47,  // "ስህተት፡ ከሰርቨሩ የመጣው መልስ አይነበብም"
        48 to R.raw.prompt_48,  // "ድምጹ በመዘጋጀት ላይ ነው..."
        49 to R.raw.prompt_49,  // "የማይነበበውን መልስ በማለፍ ላይ"
        50 to R.raw.prompt_50,  // "የድምጽ ፋይሉ ተበላሽቷል"
        51 to R.raw.prompt_51   // "የድምጽ ማጫወቻ ስህተት ተፈጥሯል"
    )
}